// These private lifecycle members remain inside one runtime chunk in each build.
// Public API and serialized data keys must never be added to this list.
export const runtimePrivateProperties = [
  "applicationId",
  "mounted",
  "handleResult",
  "isDisposed",
  "metadataFinalizers",
  "activePreservedRoots",
  "enhancementErrors",
  "trackedApplicationId",
  "disposalInProgress",
  "disposalController",
  "disposalError",
  "createOwnedObserver",
  "createOwnedTask",
  "createDocumentHost",
  "createSubscription",
  "nextOperationId",
  "releaseExpressionRuntime",
  "releaseOwnedResources",
  "initializeDirective",
  "initializeComputed",
  "reconcileRegisteredDirective",
  "mountRegisteredDirective",
  "assertDirectiveActive",
  "ownDirectiveCleanup",
  "registerDirectiveResult",
  "releaseDirectiveRecord",
  "reportLifecycle",
  "cleanupDirective",
  "cleanupTree",
  "loadSignals",
  "loadComputed",
  "scanTree",
  "allWithin",
  "setCleanup",
  "bindValue",
  "bindEffect",
  "bindModel",
  "bindEvent",
  "createComputed",
  "elementContext",
  "elementsWithin",
  "installRules",
  "installBindings",
  "applyBindings",
  "installModel",
  "writeModel",
  "readModel",
  "installEvents",
  "mountTree",
  "mountElement",
  "handleMutations",
  "releaseObserver",
  "isDestroyed",
  "onceElements",
  "debounceTimers",
  "throttleTimes",
  "directiveContext",
] as const;

export const runtimePropertyMangle = {
  properties: { regex: new RegExp("^(" + runtimePrivateProperties.join("|") + ")$") },
};
