export const detectorExpectations = [
  [
    "browser-shard-refusal",
    "red",
    /cannot authorize browser quality until an all-shard result aggregator exists/u,
    null,
  ],
  [
    "browser-empty-selection",
    "red",
    /No tests found[\s\S]*Browser quality failed/u,
    "empty-selection/playwright",
  ],
  [
    "retry-pass-is-red",
    "red",
    /1 flaky[\s\S]*production Playwright config keeps retry-passes red/u,
    "retry-pass",
  ],
  ["accessibility", "red", /button-name/u, "playwright/accessibility"],
  ["ownership-budget", "red", /Expected:\s*<= 1/u, "playwright/ownership-budget"],
  ["network-fixture", "red", /retry-detector-sabotaged/u, "playwright/network-fixture"],
  ["mobile-target", "red", /Expected:\s*>= 10000/u, "playwright/mobile-target"],
  ["reduced-motion", "red", /animationMs/u, "playwright/reduced-motion"],
  ["forced-colors", "red", /Expected:\s*> 100/u, "playwright/forced-colors"],
  ["zoom-reflow", "red", /Expected:\s*<= 0/u, "playwright/zoom-reflow"],
  ["no-javascript", "red", /Missing no-JavaScript heading/u, "playwright/no-javascript"],
  [
    "package-budget",
    "red",
    /package-budgets: Packed bytes \d+ exceed the base and optional-entry allowances/u,
    null,
  ],
  ["api-report-drift", "red", /changed the API signature/u, null],
  [
    "artifact-manifest-drift",
    "red",
    /reproducible-build: Packed file manifests differ between clean builds/u,
    null,
  ],
  ["package-release-contract-hardening", "green", /Tests\s+15 passed/u, null],
  [
    "browser-selection-green-control",
    "green",
    /browser quality: 8 projects, \d+ selected tests[\s\S]*selection=passed/u,
    "browser-green/playwright",
  ],
];
export const browserExpectations = [
  [
    "accessibility",
    "desktop-chromium",
    "@shared keyboard, error, updated, open, and disabled states remain accessible",
    "keyboard, error",
    /button-name/u,
  ],
  [
    "ownership-budget",
    "desktop-chromium",
    "@shared repeated enhancement stays inside structural ownership budgets",
    "repeated enhancement",
    /Expected:\s*<= 1/u,
  ],
  [
    "network-fixture",
    "desktop-chromium",
    "@shared proof network detects abort, delay, disconnect, malformed, retry, redirect, conflict, and partial streams",
    "proof network",
    /retry-detector-sabotaged/u,
  ],
  [
    "mobile-target",
    "mobile-touch",
    "@mobile touch controls meet the documented target and reflow contracts",
    "touch controls",
    /Expected:\s*>= 10000/u,
  ],
  [
    "reduced-motion",
    "reduced-motion",
    "@motion reduced-motion preference reaches the document",
    "reduced-motion preference",
    /animationMs/u,
  ],
  [
    "forced-colors",
    "forced-colors",
    "@color forced colors preserve visible focus and native controls",
    "forced colors",
    /Expected:\s*> 100/u,
  ],
  [
    "zoom-reflow",
    "zoom-reflow",
    "@zoom content reflows at 200 percent",
    "content reflows",
    /Expected:\s*<= 0/u,
  ],
  [
    "no-javascript",
    "javascript-disabled",
    "@nojs native content and disclosure remain usable without JavaScript",
    "native content",
    /Missing no-JavaScript heading/u,
  ],
  [
    "retry-pass-is-red",
    "quality-selftest",
    "@selftest production Playwright config keeps retry-passes red",
    null,
    /Expected:\s*> 0/u,
  ],
];

export const configuredProjects = Object.freeze([
  "desktop-chromium",
  "desktop-firefox",
  "desktop-webkit",
  "webmcp-chromium",
  "mobile-touch",
  "reduced-motion",
  "forced-colors",
  "zoom-reflow",
  "javascript-disabled",
]);
export const selectionProjects = Object.freeze(
  configuredProjects.filter((project) => project !== "webmcp-chromium"),
);
export const failedGateExpectations = {
  package: {
    schema: "jqstar-package-quality/1",
    mode: "package",
    checks: [
      "build",
      "api-report",
      "pack",
      "package-budgets",
      "exports-and-files",
      "publint",
      "are-the-types-wrong",
      "refresh-package-subject",
      "installed-consumer",
      "qunit-consumer",
      "browser-consumers",
      "bundle-sentinel",
      "copy-in-registry",
    ],
    failure: "package-budgets",
    error: /^Packed bytes \d+ exceed the base and optional-entry allowances\.$/u,
  },
  release: {
    schema: "jqstar-release-quality/1",
    mode: "release",
    checks: [
      "clean-install",
      "reproducible-build",
      "sbom",
      "licenses",
      "provenance-eligibility",
      "supported-toolchain",
      "packed-self-hosted",
    ],
    failure: "reproducible-build",
    error: /^Packed file manifests differ between clean builds \(1 changed; budget 0\)\.$/u,
  },
};
