import jQuery from "jquery";
import { installStar } from "./compatibility";

installStar(jQuery);

export { installStar } from "./compatibility";
export type { StarInstallOptions } from "./compatibility";
export { installStarCore } from "./trusted-runtime";
export type { StarCoreInstallOptions } from "./trusted-runtime";
export { createRenderAdapter, StarRenderTransactionError } from "./render-adapter";
export type {
  StarRenderAdapter,
  StarRenderBeginOptions,
  StarRenderTransaction,
} from "./render-adapter";
export { StarDisposalError } from "./disposal";
export type {
  StarDisposalCategory,
  StarDisposalFailure,
  StarDisposalReport,
  StarDisposalResource,
} from "./disposal";
export {
  clearExpressionCache,
  compileStatement,
  compileValue,
  createTrustedExpressionEngine,
} from "./expression";
export type {
  StarExpressionEngine,
  StarExpressionError,
  StarExpressionLocation,
  StarStatementEvaluator,
  StarValueEvaluator,
} from "./expression";
export type {
  StarDirective,
  StarDirectiveAttribute,
  StarDirectiveCleanup,
  StarDirectiveContext,
  StarDirectiveExactMatcher,
  StarDirectiveMatcher,
  StarDirectivePrefixMatcher,
  StarDirectiveTask,
  StarExpressionHelperScope,
  StarParsedDirectiveAttribute,
} from "./directive";
export { STAR_PLUGIN_API_VERSION } from "./plugin";
export type {
  StarPlugin,
  StarPluginActivation,
  StarPluginApplicationHook,
  StarPluginCleanup,
  StarPluginDocumentHost,
  StarPluginFacade,
  StarPluginRegistrar,
  StarPluginResourceKind,
} from "./plugin";
export type {
  StarActionCancelledObservation,
  StarActionCompletedObservation,
  StarActionFailedObservation,
  StarActionOperationObservation,
  StarActionStartedObservation,
  StarOperationCancellationReason,
  StarOperationError,
  StarOperationKind,
  StarOperationObservation,
  StarOperationObserver,
  StarOperationObserverErrorHandler,
  StarOperationOwner,
  StarOperationSubscriptionOptions,
  StarOperationTerminalPhase,
  StarOperationUnsubscribe,
  StarRequestCancelledObservation,
  StarRequestCompletedObservation,
  StarRequestFailedObservation,
  StarRequestOperationMetadata,
  StarRequestOperationObservation,
  StarRequestProgressObservation,
  StarRequestRetryingObservation,
  StarRequestStartedObservation,
} from "./observation";
export {
  StarProtocolBodyOwnershipError,
  StarProtocolSelectionError,
  StarProtocolValidationError,
} from "./protocol";
export type {
  StarProtocolBodyLease,
  StarProtocolCompatibilityEvent,
  StarProtocolEmptyResponseHandler,
  StarProtocolExactMediaMatcher,
  StarProtocolFormMetadata,
  StarProtocolMediaMatcher,
  StarProtocolProfileDefinition,
  StarProtocolRequestInput,
  StarProtocolRequestPreparer,
  StarProtocolRequestWriter,
  StarProtocolResponseAdapter,
  StarProtocolResponseCapabilities,
  StarProtocolResponseHandler,
  StarProtocolResponseMetadata,
  StarProtocolSerializedPayload,
  StarProtocolStreamConsumer,
  StarProtocolSuffixMediaMatcher,
} from "./protocol";
export {
  StarRequestMiddlewareNextError,
  StarRequestMiddlewareValidationError,
} from "./request-middleware";
export type {
  StarRequestBodyKind,
  StarRequestBodyMetadata,
  StarRequestDescriptor,
  StarRequestMiddleware,
  StarRequestMiddlewareCancelledOutcome,
  StarRequestMiddlewareCompletedOutcome,
  StarRequestMiddlewareContext,
  StarRequestMiddlewareDefinition,
  StarRequestMiddlewareFailedOutcome,
  StarRequestMiddlewareNext,
  StarRequestMiddlewareOutcome,
} from "./request-middleware";
export {
  cancelElementRequests,
  cancelRequests,
  createBackendAction,
  dynamicBackendAction,
  executeBackendRequest,
} from "./fetch";
export { patchElements, patchSignals } from "./patch";
export { nextUpdate } from "./reactivity";
export { parseSSE, SSEParser, sseDataFields } from "./sse";
export type {
  BackendActionOptions,
  BackendMethod,
  ComputedDefinition,
  ComputedRecord,
  ComboboxTarget,
  CarouselTarget,
  ContextMenuTarget,
  CalendarDate,
  CalendarTarget,
  DataTableSort,
  DataTableSortDirection,
  DataTableTarget,
  DatePickerTarget,
  DateRangePickerTarget,
  DOMValue,
  DialogOpenOptions,
  DialogTarget,
  DisclosureTarget,
  EventBinding,
  EventOptions,
  FetchLifecycleDetail,
  FormTarget,
  FileUploadTarget,
  MultiSelectTarget,
  TransferListTarget,
  TimePickerTarget,
  ColorPickerTarget,
  RatingTarget,
  MessageScrollerTarget,
  MessageScrollerLatestOptions,
  SearchFieldTarget,
  FeedTarget,
  FeedState,
  FeedCompleteOptions,
  FeedResetOptions,
  QuestionnaireTarget,
  QuestionnaireAnswer,
  QuestionnaireAnswers,
  ChartTarget,
  ChartType,
  ChartSeries,
  ChartData,
  CodeBlockTarget,
  ClipboardTarget,
  ClipboardState,
  EditableTarget,
  LogViewerTarget,
  LogLevel,
  LogFilter,
  LogEntryInput,
  LogViewerState,
  JSONViewerTarget,
  CountdownTarget,
  CountdownUntil,
  CountdownState,
  HoverCardTarget,
  InputOTPTarget,
  ModelBinding,
  MenuTarget,
  MenubarTarget,
  TreeTarget,
  NumberFieldTarget,
  PasswordFieldTarget,
  PatchElementsOptions,
  PatchMode,
  PatchNamespace,
  PatchSignalsOptions,
  PaginationTarget,
  PopoverTarget,
  RangeCalendarTarget,
  RangeCalendarValue,
  ResizableTarget,
  SidebarTarget,
  RequestCancellation,
  RetryMode,
  SSEMessage,
  SelectTarget,
  SignalFilter,
  StarAction,
  StarComboboxStatic,
  StarContextMenuStatic,
  StarCalendarStatic,
  StarCarouselStatic,
  StarRangeCalendarStatic,
  StarDataTableStatic,
  StarPaginationStatic,
  StarDatePickerStatic,
  StarDateRangePickerStatic,
  StarContext,
  StarCoreStatic,
  StarDefinition,
  StarInstalledJQuery,
  StarDialogStatic,
  StarDisclosureStatic,
  StarInstance,
  StarJQueryMethod,
  StarFormStatic,
  StarFileUploadStatic,
  StarMultiSelectStatic,
  StarTransferListStatic,
  StarTimePickerStatic,
  StarColorPickerStatic,
  StarRatingStatic,
  StarMessageScrollerStatic,
  StarSearchFieldStatic,
  StarFeedStatic,
  StarQuestionnaireStatic,
  StarChartStatic,
  StarCodeBlockStatic,
  StarClipboardStatic,
  StarEditableStatic,
  StarLogViewerStatic,
  StarJSONViewerStatic,
  StarCountdownStatic,
  StarFormErrorOptions,
  StarFormErrors,
  StarFormValidateOptions,
  StarHoverCardStatic,
  StarInputOTPStatic,
  StarMenuStatic,
  StarMenubarStatic,
  StarTreeStatic,
  StarNumberFieldStatic,
  StarPasswordFieldStatic,
  StarResizableStatic,
  StarSidebarStatic,
  StarSelectStatic,
  StarPopoverStatic,
  StarStatic,
  StarTabsStatic,
  StarToastStatic,
  StarTooltipStatic,
  StarToggleGroupStatic,
  StarToggleStatic,
  StarTagsInputStatic,
  StarToolbarStatic,
  StarStepperStatic,
  StarSortableStatic,
  StarUIStatic,
  TabTarget,
  TabsTarget,
  ToastOptions,
  ToastPriority,
  ToastTarget,
  ToastVariant,
  TooltipTarget,
  ToggleGroupTarget,
  ToggleTarget,
  ToolbarTarget,
  StepperTarget,
  SortableTarget,
  TagsInputTarget,
  StateRecord,
  UIRule,
  Value,
} from "./types";
