export const CSP_GRAMMAR_VERSION = "jqstar-csp-expression/1" as const;
export const CSP_CONTRACT_DIGEST =
  "2726c0377afac773700d0ec2334a0cb88bc246e67ad80b63b583ff5a5e5d349f" as const;

export const CSP_ENTRY_KINDS = Object.freeze(["value", "statement"] as const);
export type CSPEntryKind = (typeof CSP_ENTRY_KINDS)[number];

export const CSP_TOKEN_KINDS = Object.freeze([
  "identifier",
  "signal",
  "number",
  "string",
  "keyword",
  "punctuator",
  "operator",
  "eof",
] as const);
export type CSPTokenKind = (typeof CSP_TOKEN_KINDS)[number];

export const CSP_NODE_KINDS = Object.freeze([
  "program",
  "expression-statement",
  "return-statement",
  "literal",
  "array-literal",
  "object-literal",
  "object-property",
  "binding",
  "signal",
  "member",
  "unary",
  "binary",
  "logical",
  "conditional",
  "assignment",
  "update",
  "await",
  "action-call",
  "helper-call",
  "jquery-call",
  "method-call",
] as const);
export type CSPNodeKind = (typeof CSP_NODE_KINDS)[number];

export const CSP_PRODUCTIONS = Object.freeze([
  "value-input",
  "statement-input",
  "statement-list",
  "expression-statement",
  "return-statement",
  "assignment-expression",
  "conditional-expression",
  "nullish-expression",
  "logical-or-expression",
  "logical-and-expression",
  "equality-expression",
  "relational-expression",
  "additive-expression",
  "multiplicative-expression",
  "unary-expression",
  "await-expression",
  "update-expression",
  "member-expression",
  "computed-member",
  "primary-expression",
  "literal",
  "array-literal",
  "object-literal",
  "object-property",
  "binding-reference",
  "signal-reference",
  "action-shorthand",
  "action-call",
  "helper-call",
  "jquery-call",
  "method-call",
  "argument-list",
] as const);
export const CSP_LIMITS = Object.freeze({
  sourceLength: 2_048,
  tokens: 512,
  nesting: 16,
  astNodes: 256,
  literalEntries: 64,
  pathSegments: 8,
  callArguments: 8,
  evaluationSteps: 128,
  collectionSize: 128,
  asyncChain: 8,
});

export const CSP_DIAGNOSTICS = Object.freeze({
  sourceType: Object.freeze({ code: "CSP_SOURCE_TYPE", phase: "compile" }),
  sourceLength: Object.freeze({ code: "CSP_LIMIT_SOURCE_LENGTH", phase: "compile" }),
  invalidCharacter: Object.freeze({ code: "CSP_TOKEN_INVALID_CHARACTER", phase: "compile" }),
  invalidEscape: Object.freeze({ code: "CSP_TOKEN_INVALID_ESCAPE", phase: "compile" }),
  numberFormat: Object.freeze({ code: "CSP_TOKEN_NUMBER", phase: "compile" }),
  unterminatedString: Object.freeze({
    code: "CSP_TOKEN_UNTERMINATED_STRING",
    phase: "compile",
  }),
  unexpectedToken: Object.freeze({ code: "CSP_PARSE_UNEXPECTED_TOKEN", phase: "compile" }),
  expectedToken: Object.freeze({ code: "CSP_PARSE_EXPECTED_TOKEN", phase: "compile" }),
  trailingInput: Object.freeze({ code: "CSP_PARSE_TRAILING_INPUT", phase: "compile" }),
  unsupportedSyntax: Object.freeze({ code: "CSP_PARSE_UNSUPPORTED_SYNTAX", phase: "compile" }),
  duplicateKey: Object.freeze({ code: "CSP_PARSE_DUPLICATE_KEY", phase: "compile" }),
  deniedIdentifier: Object.freeze({ code: "CSP_CAPABILITY_IDENTIFIER", phase: "compile" }),
  deniedProperty: Object.freeze({ code: "CSP_CAPABILITY_PROPERTY", phase: "evaluate" }),
  deniedCall: Object.freeze({ code: "CSP_CAPABILITY_CALL", phase: "evaluate" }),
  invalidLvalue: Object.freeze({ code: "CSP_CAPABILITY_LVALUE", phase: "compile" }),
  deniedAccessor: Object.freeze({ code: "CSP_CAPABILITY_ACCESSOR", phase: "evaluate" }),
  deniedValue: Object.freeze({ code: "CSP_CAPABILITY_VALUE", phase: "evaluate" }),
  propertyAbsent: Object.freeze({ code: "CSP_PROPERTY_ABSENT", phase: "evaluate" }),
  numericResult: Object.freeze({ code: "CSP_EVALUATE_NUMBER", phase: "evaluate" }),
  operandType: Object.freeze({ code: "CSP_EVALUATE_TYPE", phase: "evaluate" }),
  cycle: Object.freeze({ code: "CSP_EVALUATE_CYCLE", phase: "evaluate" }),
  asyncValue: Object.freeze({ code: "CSP_ASYNC_VALUE", phase: "evaluate" }),
  asyncRejection: Object.freeze({ code: "CSP_ASYNC_REJECTION", phase: "evaluate" }),
  engineDisposed: Object.freeze({ code: "CSP_ENGINE_DISPOSED", phase: "evaluate" }),
  tokenLimit: Object.freeze({ code: "CSP_LIMIT_TOKENS", phase: "compile" }),
  nestingLimit: Object.freeze({ code: "CSP_LIMIT_NESTING", phase: "compile" }),
  nodeLimit: Object.freeze({ code: "CSP_LIMIT_AST_NODES", phase: "compile" }),
  literalLimit: Object.freeze({ code: "CSP_LIMIT_LITERAL_ENTRIES", phase: "compile" }),
  pathLimit: Object.freeze({ code: "CSP_LIMIT_PATH_SEGMENTS", phase: "compile" }),
  argumentLimit: Object.freeze({ code: "CSP_LIMIT_CALL_ARGUMENTS", phase: "compile" }),
  stepLimit: Object.freeze({ code: "CSP_LIMIT_EVALUATION_STEPS", phase: "evaluate" }),
  collectionLimit: Object.freeze({ code: "CSP_LIMIT_COLLECTION_SIZE", phase: "evaluate" }),
  asyncLimit: Object.freeze({ code: "CSP_LIMIT_ASYNC_CHAIN", phase: "evaluate" }),
} as const);

export type CSPDiagnostic = (typeof CSP_DIAGNOSTICS)[keyof typeof CSP_DIAGNOSTICS];
export type CSPDiagnosticCode = CSPDiagnostic["code"];
export type CSPDiagnosticPhase = CSPDiagnostic["phase"];

export const CSP_METHODS = Object.freeze({
  jquery: Object.freeze([
    "addClass",
    "attr",
    "children",
    "closest",
    "css",
    "eq",
    "fadeIn",
    "fadeOut",
    "filter",
    "find",
    "first",
    "hasClass",
    "hide",
    "html",
    "is",
    "last",
    "not",
    "parent",
    "prop",
    "removeClass",
    "show",
    "siblings",
    "text",
    "toggle",
    "toggleClass",
    "val",
  ]),
  string: Object.freeze([
    "charAt",
    "endsWith",
    "includes",
    "slice",
    "startsWith",
    "substring",
    "toLowerCase",
    "toUpperCase",
    "trim",
  ]),
  array: Object.freeze(["at", "includes", "indexOf", "join", "slice"]),
  event: Object.freeze(["preventDefault", "stopPropagation"]),
});
